[program:justqiuv2-rewrite-api]
directory=/home/mugiew/projects/justqiuv2-rewrite-go
command=/home/mugiew/projects/justqiuv2-rewrite-go/bin/server
user=mugiew
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
stdout_logfile=/home/mugiew/projects/justqiuv2-rewrite-go/logs/api.out.log
stderr_logfile=/home/mugiew/projects/justqiuv2-rewrite-go/logs/api.err.log
environment=HOME="/home/mugiew"

